import * as React from "react";
import {HTMLAttributes} from "react";

// Attention: This file is generated by "yarn icon", do not modify

// prettier-ignore
export enum IconClass {/* {1} */}

interface Props extends HTMLAttributes<HTMLSpanElement> {
  type: IconClass;
  text?: string;
  textPosition?: "left" | "right";
}

export default class Component extends React.PureComponent<Props> {
  public static defaultProps: Props = {
    type: null as any,
    textPosition: "right",
  };

  public render() {
    const {type, text, textPosition, className, ...restProps} = this.props;
    if (text) {
      if (textPosition === "left") {
        return (
          <div className={`iconfont-with-text-on-left ${className ? className : ""}`} {...restProps}>
            <span>{text}</span>
            <i className={`iconfont ${type}`} {...restProps} />
          </div>
        );
      } else {
        return (
          <div className={`iconfont-with-text-on-right ${className ? className : ""}`} {...restProps}>
            <i className={`iconfont ${type}`} {...restProps} />
            <span>{text}</span>
          </div>
        );
      }
    } else {
      return <i className={`iconfont ${type} ${className ? className : ""}`} {...restProps} />;
    }
  }
}
